/// One segment of an f-string literal.
#[derive(Debug, Clone, PartialEq)]
pub enum FStringPart {
    /// Plain text fragment (already escape-processed).
    Literal(String),
    /// Raw source text for the expression, plus optional conversion flag and format spec.
    Expr {
        src: String,
        conversion: Option<char>,
        format_spec: Option<String>,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Int(i64),
    Float(f64),
    Str(String),
    FString(Vec<FStringPart>),
    Ident(String),
    // Arithmetic
    Plus,
    Minus,
    Star,
    StarStar,
    Slash,
    SlashSlash,
    Percent,
    At,
    // Augmented assignment
    PlusAssign,
    MinusAssign,
    StarAssign,
    StarStarAssign,
    SlashAssign,
    SlashSlashAssign,
    PercentAssign,
    AtAssign,
    AmpersandAssign,
    PipeAssign,
    CaretAssign,
    LShiftAssign,
    RShiftAssign,
    // Bitwise
    Ampersand,
    Pipe,
    Caret,
    Tilde,
    LShift,
    RShift,
    // Delimiters
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Colon,
    Walrus, // :=
    Semicolon,
    Dot,
    Arrow, // ->
    // Comparison / assignment
    Assign,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    // Keywords
    And,
    Or,
    Not,
    If,
    Elif,
    Else,
    While,
    For,
    In,
    Def,
    Class,
    With,
    Try,
    Except,
    Finally,
    Raise,
    As,
    Import,
    From,
    Global,
    Nonlocal,
    Return,
    Yield,
    Break,
    Continue,
    Pass,
    Del,
    Assert,
    Lambda,
    Is,
    True,
    False,
    None,
    // Layout
    Newline,
    Indent,
    Dedent,
    Eof,
}
