[package]
name = "pyrust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pyrust"
path = "src/main.rs"

[dependencies]
indexmap = "2"
num-bigint = "0.4"
rustyline = "14"
smallvec = "1"
pyrust-core = { path = "../pyrust-core" }
pyrust-builtins = { path = "../pyrust-builtins" }
pyrust-derive = { path = "../pyrust-derive" }
