//! Per-module registration slices for built-in callables.
//!
//! Each module file declares its content via `pyrust_module! { … }`
//! (which generates `REGS: &[BuiltinReg]` and `module() -> Value`).
//! This `mod.rs` is the **single place to list every built-in module**
//! — adding a new module requires editing only the
//! `pyrust_builtin_modules!` call below.  Both
//! [`crate::builtin_registry::REGISTRY`] (the function-level lookup) and
//! [`load_builtin_module`] (the `import name` entry point) read from the
//! list this macro produces, so neither has to be touched when a new
//! module is added.

use crate::builtin_registry::BuiltinReg;
use crate::value::Value;

/// Declares the list of built-in modules.  For each `ident`, the macro
/// emits `pub mod ident;` and registers `ident::REGS` + `ident::module`
/// so [`all_regs`] and [`load_builtin_module`] see them automatically.
///
/// Each module file must define a `pub(crate) const REGS:
/// &[BuiltinReg]` and a `pub(crate) fn module() -> Value` — both
/// generated by the `pyrust_derive::pyrust_module!` macro.
macro_rules! pyrust_builtin_modules {
    ($($name:ident),* $(,)?) => {
        $(
            pub mod $name;
        )*

        /// Concatenate every per-module `REGS` slice — consumed by
        /// [`crate::builtin_registry::REGISTRY`] on first use.
        pub(crate) fn all_regs() -> Vec<BuiltinReg> {
            let mut all: Vec<BuiltinReg> = Vec::new();
            $(
                all.extend_from_slice($name::REGS);
            )*
            all
        }

        /// Resolve `import name` to its built-in module value, if any.
        /// Replaces the hand-maintained `match name { "math" => …, … }`
        /// previously sitting inside `env.rs::load_module`.
        pub fn load_builtin_module(name: &str) -> Option<Value> {
            match name {
                $(
                    stringify!($name) => Some($name::module()),
                )*
                _ => None,
            }
        }
    };
}

// The single source of truth for the set of built-in modules pyrust
// ships.  Add the module file under this directory, register a line
// here, and `import <name>` + every callable in it works — `env.rs`
// and `builtin_registry.rs` need no edits.
pyrust_builtin_modules! {
    math,
    sys,
}
