/// Convert a finite `f64` to a `BigInt` `Value`, raising the CPython-matching
/// Python exceptions for non-finite inputs:
/// - `OverflowError` for ±infinity
/// - `ValueError` for NaN
///
/// For finite floats the fractional part is discarded (truncation toward zero),
/// matching CPython's `int(float)` / `math.floor` / `math.ceil` semantics.
pub(crate) fn float_to_bigint(f: f64) -> crate::error::Result<Value> {
    use crate::value::PyBigInt;
    use num_traits::FromPrimitive;
    if f.is_nan() {
        return Err(crate::error::PyError::named(
            "ValueError",
            "cannot convert float NaN to integer".to_string(),
        ));
    }
    if f.is_infinite() {
        return Err(crate::error::PyError::named(
            "OverflowError",
            "cannot convert float infinity to integer".to_string(),
        ));
    }
    // Truncate toward zero (matching CPython's behaviour for floor/ceil callers
    // that have already applied their own rounding before calling here).
    let n = PyBigInt::from_f64(f.trunc()).expect("finite f64 must convert to BigInt");
    Ok(Value::bigint(n))
}

/// Coerce a `Value` to `f64` for numeric ops.  Returns the raw `f64` on
/// success or `None` for non-numeric types (including BigInt values that
/// overflow to ±inf) — the caller chooses the error wording so
/// CPython-parity messages stay precise at each call site.
///
/// For BigInt, use [`value_to_float`] instead when you need the
/// CPython-matching `OverflowError` (rather than a `TypeError`) for integers
/// too large to represent as a finite `f64`.
pub(crate) fn try_value_to_float(v: &Value) -> Option<f64> {
    match v.kind() {
        ValueKind::Float(f) => Some(f),
        ValueKind::Int(i) => Some(i as f64),
        ValueKind::Bool(b) => Some(if b { 1.0 } else { 0.0 }),
        ValueKind::BigInt(b) => {
            // `ToPrimitive::to_f64` always returns `Some` for BigInt (never
            // `None`); the result is `±inf` when the magnitude exceeds f64
            // range.  Filter those out so callers receive `None` rather than a
            // silent infinity that would bypass CPython's OverflowError.
            // Callers that need the proper OverflowError should use
            // `value_to_float` instead.
            b.to_f64().filter(|f| f.is_finite())
        }
        _ => None,
    }
}

/// Coerce a `Value` to `f64` with the `math`/builtins-style error message,
/// matching CPython's `math.sqrt`-family error wording.
///
/// Raises `OverflowError` (not `TypeError`) when a `BigInt` argument is too
/// large to represent as a finite `f64`, mirroring CPython's behaviour:
/// `math.sqrt(2**10000)` → `OverflowError: int too large to convert to float`.
pub(crate) fn value_to_float(v: &Value, ctx: &str) -> Result<f64> {
    // Handle BigInt before falling through to try_value_to_float so we can
    // distinguish a non-numeric type (TypeError) from an overflow (OverflowError).
    if let ValueKind::BigInt(b) = v.kind() {
        let f = b.to_f64().unwrap_or(f64::INFINITY);
        return if f.is_finite() {
            Ok(f)
        } else {
            Err(PyError::named(
                "OverflowError",
                "int too large to convert to float".to_string(),
            ))
        };
    }
    try_value_to_float(v).ok_or_else(|| {
        PyError::named(
            "TypeError",
            format!("{ctx}: a float is required, not {}", v.repr_raw()),
        )
    })
}

// `make_math_module()` / `make_sys_module()` removed — both are now
// generated by the `pyrust_module!` macro inside
// `crates/pyrust/src/builtin_modules/{math,sys}.rs`.  See
// `docs/builtin-migration.md` for the recipe.
