// `errno` module — POSIX error-code integer constants and the `errorcode`
// reverse-mapping dict.
//
// Exposes the standard set of POSIX errno values that CPython 3.12 exports
// on Linux.  The `errorcode` dict maps each integer code to its canonical
// name string (the name that wins when multiple names share the same value,
// matching CPython's behaviour: e.g. 11 → "EAGAIN", 35 → "EDEADLOCK",
// 95 → "ENOTSUP").
//
// Reference: <https://docs.python.org/3/library/errno.html>

use crate::value::{PyKey, Value};
use indexmap::IndexMap;
use pyrust_derive::pyrust_module;

/// Build the `errorcode` dict: maps int error-code → canonical name string.
///
/// The insertion order determines which name wins when two names share the
/// same integer value — the *last* inserted entry wins (IndexMap lookup by
/// key always returns the associated value, but duplicate key insertions
/// overwrite; in CPython the winner is the last alias processed by the C
/// extension).  Verified against `python3.12 -c "import errno;
/// print(errno.errorcode[11], errno.errorcode[35], errno.errorcode[95])"`:
///   11 → EAGAIN, 35 → EDEADLOCK, 95 → ENOTSUP.
fn make_errorcode() -> Value {
    // (code, canonical_name) pairs.  When two names share the same code,
    // list the one that should appear in errorcode *last* so it overwrites
    // the earlier entry.
    let entries: &[(i64, &str)] = &[
        (1, "EPERM"),
        (2, "ENOENT"),
        (3, "ESRCH"),
        (4, "EINTR"),
        (5, "EIO"),
        (6, "ENXIO"),
        (7, "E2BIG"),
        (8, "ENOEXEC"),
        (9, "EBADF"),
        (10, "ECHILD"),
        // EWOULDBLOCK=11 is an alias for EAGAIN; EAGAIN wins in errorcode.
        (11, "EWOULDBLOCK"),
        (11, "EAGAIN"),
        (12, "ENOMEM"),
        (13, "EACCES"),
        (14, "EFAULT"),
        (15, "ENOTBLK"),
        (16, "EBUSY"),
        (17, "EEXIST"),
        (18, "EXDEV"),
        (19, "ENODEV"),
        (20, "ENOTDIR"),
        (21, "EISDIR"),
        (22, "EINVAL"),
        (23, "ENFILE"),
        (24, "EMFILE"),
        (25, "ENOTTY"),
        (26, "ETXTBSY"),
        (27, "EFBIG"),
        (28, "ENOSPC"),
        (29, "ESPIPE"),
        (30, "EROFS"),
        (31, "EMLINK"),
        (32, "EPIPE"),
        (33, "EDOM"),
        (34, "ERANGE"),
        // EDEADLK=35 is an alias; EDEADLOCK wins in errorcode.
        (35, "EDEADLK"),
        (35, "EDEADLOCK"),
        (36, "ENAMETOOLONG"),
        (37, "ENOLCK"),
        (38, "ENOSYS"),
        (39, "ENOTEMPTY"),
        (40, "ELOOP"),
        (42, "ENOMSG"),
        (43, "EIDRM"),
        (44, "ECHRNG"),
        (45, "EL2NSYNC"),
        (46, "EL3HLT"),
        (47, "EL3RST"),
        (48, "ELNRNG"),
        (49, "EUNATCH"),
        (50, "ENOCSI"),
        (51, "EL2HLT"),
        (52, "EBADE"),
        (53, "EBADR"),
        (54, "EXFULL"),
        (55, "ENOANO"),
        (56, "EBADRQC"),
        (57, "EBADSLT"),
        (59, "EBFONT"),
        (60, "ENOSTR"),
        (61, "ENODATA"),
        (62, "ETIME"),
        (63, "ENOSR"),
        (64, "ENONET"),
        (65, "ENOPKG"),
        (66, "EREMOTE"),
        (67, "ENOLINK"),
        (68, "EADV"),
        (69, "ESRMNT"),
        (70, "ECOMM"),
        (71, "EPROTO"),
        (72, "EMULTIHOP"),
        (73, "EDOTDOT"),
        (74, "EBADMSG"),
        (75, "EOVERFLOW"),
        (76, "ENOTUNIQ"),
        (77, "EBADFD"),
        (78, "EREMCHG"),
        (79, "ELIBACC"),
        (80, "ELIBBAD"),
        (81, "ELIBSCN"),
        (82, "ELIBMAX"),
        (83, "ELIBEXEC"),
        (84, "EILSEQ"),
        (85, "ERESTART"),
        (86, "ESTRPIPE"),
        (87, "EUSERS"),
        (88, "ENOTSOCK"),
        (89, "EDESTADDRREQ"),
        (90, "EMSGSIZE"),
        (91, "EPROTOTYPE"),
        (92, "ENOPROTOOPT"),
        (93, "EPROTONOSUPPORT"),
        (94, "ESOCKTNOSUPPORT"),
        // EOPNOTSUPP=95 is an alias; ENOTSUP wins in errorcode.
        (95, "EOPNOTSUPP"),
        (95, "ENOTSUP"),
        (96, "EPFNOSUPPORT"),
        (97, "EAFNOSUPPORT"),
        (98, "EADDRINUSE"),
        (99, "EADDRNOTAVAIL"),
        (100, "ENETDOWN"),
        (101, "ENETUNREACH"),
        (102, "ENETRESET"),
        (103, "ECONNABORTED"),
        (104, "ECONNRESET"),
        (105, "ENOBUFS"),
        (106, "EISCONN"),
        (107, "ENOTCONN"),
        (108, "ESHUTDOWN"),
        (109, "ETOOMANYREFS"),
        (110, "ETIMEDOUT"),
        (111, "ECONNREFUSED"),
        (112, "EHOSTDOWN"),
        (113, "EHOSTUNREACH"),
        (114, "EALREADY"),
        (115, "EINPROGRESS"),
        (116, "ESTALE"),
        (117, "EUCLEAN"),
        (118, "ENOTNAM"),
        (119, "ENAVAIL"),
        (120, "EISNAM"),
        (121, "EREMOTEIO"),
        (122, "EDQUOT"),
        (123, "ENOMEDIUM"),
        (124, "EMEDIUMTYPE"),
        (125, "ECANCELED"),
        (126, "ENOKEY"),
        (127, "EKEYEXPIRED"),
        (128, "EKEYREVOKED"),
        (129, "EKEYREJECTED"),
        (130, "EOWNERDEAD"),
        (131, "ENOTRECOVERABLE"),
        (132, "ERFKILL"),
    ];
    let mut map: IndexMap<PyKey, Value> = IndexMap::new();
    for (code, name) in entries {
        map.insert(PyKey::Int(*code), Value::string(*name));
    }
    Value::dict(map)
}

pyrust_module! {
    constants {
        // Standard POSIX error codes — values match Linux CPython 3.12.
        "EPERM"             => Value::int(1),
        "ENOENT"            => Value::int(2),
        "ESRCH"             => Value::int(3),
        "EINTR"             => Value::int(4),
        "EIO"               => Value::int(5),
        "ENXIO"             => Value::int(6),
        "E2BIG"             => Value::int(7),
        "ENOEXEC"           => Value::int(8),
        "EBADF"             => Value::int(9),
        "ECHILD"            => Value::int(10),
        "EAGAIN"            => Value::int(11),
        "ENOMEM"            => Value::int(12),
        "EACCES"            => Value::int(13),
        "EFAULT"            => Value::int(14),
        "ENOTBLK"           => Value::int(15),
        "EBUSY"             => Value::int(16),
        "EEXIST"            => Value::int(17),
        "EXDEV"             => Value::int(18),
        "ENODEV"            => Value::int(19),
        "ENOTDIR"           => Value::int(20),
        "EISDIR"            => Value::int(21),
        "EINVAL"            => Value::int(22),
        "ENFILE"            => Value::int(23),
        "EMFILE"            => Value::int(24),
        "ENOTTY"            => Value::int(25),
        "ETXTBSY"           => Value::int(26),
        "EFBIG"             => Value::int(27),
        "ENOSPC"            => Value::int(28),
        "ESPIPE"            => Value::int(29),
        "EROFS"             => Value::int(30),
        "EMLINK"            => Value::int(31),
        "EPIPE"             => Value::int(32),
        "EDOM"              => Value::int(33),
        "ERANGE"            => Value::int(34),
        "EDEADLK"           => Value::int(35),
        "ENAMETOOLONG"      => Value::int(36),
        "ENOLCK"            => Value::int(37),
        "ENOSYS"            => Value::int(38),
        "ENOTEMPTY"         => Value::int(39),
        "ELOOP"             => Value::int(40),
        // EWOULDBLOCK is an alias for EAGAIN on Linux.
        "EWOULDBLOCK"       => Value::int(11),
        "ENOMSG"            => Value::int(42),
        "EIDRM"             => Value::int(43),
        "ECHRNG"            => Value::int(44),
        "EL2NSYNC"          => Value::int(45),
        "EL3HLT"            => Value::int(46),
        "EL3RST"            => Value::int(47),
        "ELNRNG"            => Value::int(48),
        "EUNATCH"           => Value::int(49),
        "ENOCSI"            => Value::int(50),
        "EL2HLT"            => Value::int(51),
        "EBADE"             => Value::int(52),
        "EBADR"             => Value::int(53),
        "EXFULL"            => Value::int(54),
        "ENOANO"            => Value::int(55),
        "EBADRQC"           => Value::int(56),
        "EBADSLT"           => Value::int(57),
        "EBFONT"            => Value::int(59),
        "ENOSTR"            => Value::int(60),
        "ENODATA"           => Value::int(61),
        "ETIME"             => Value::int(62),
        "ENOSR"             => Value::int(63),
        "ENONET"            => Value::int(64),
        "ENOPKG"            => Value::int(65),
        "EREMOTE"           => Value::int(66),
        "ENOLINK"           => Value::int(67),
        "EADV"              => Value::int(68),
        "ESRMNT"            => Value::int(69),
        "ECOMM"             => Value::int(70),
        "EPROTO"            => Value::int(71),
        "EMULTIHOP"         => Value::int(72),
        "EDOTDOT"           => Value::int(73),
        "EBADMSG"           => Value::int(74),
        "EOVERFLOW"         => Value::int(75),
        "ENOTUNIQ"          => Value::int(76),
        "EBADFD"            => Value::int(77),
        "EREMCHG"           => Value::int(78),
        "ELIBACC"           => Value::int(79),
        "ELIBBAD"           => Value::int(80),
        "ELIBSCN"           => Value::int(81),
        "ELIBMAX"           => Value::int(82),
        "ELIBEXEC"          => Value::int(83),
        "EILSEQ"            => Value::int(84),
        "ERESTART"          => Value::int(85),
        "ESTRPIPE"          => Value::int(86),
        "EUSERS"            => Value::int(87),
        "ENOTSOCK"          => Value::int(88),
        "EDESTADDRREQ"      => Value::int(89),
        "EMSGSIZE"          => Value::int(90),
        "EPROTOTYPE"        => Value::int(91),
        "ENOPROTOOPT"       => Value::int(92),
        "EPROTONOSUPPORT"   => Value::int(93),
        "ESOCKTNOSUPPORT"   => Value::int(94),
        "EOPNOTSUPP"        => Value::int(95),
        // ENOTSUP is an alias for EOPNOTSUPP on Linux.
        "ENOTSUP"           => Value::int(95),
        "EPFNOSUPPORT"      => Value::int(96),
        "EAFNOSUPPORT"      => Value::int(97),
        "EADDRINUSE"        => Value::int(98),
        "EADDRNOTAVAIL"     => Value::int(99),
        "ENETDOWN"          => Value::int(100),
        "ENETUNREACH"       => Value::int(101),
        "ENETRESET"         => Value::int(102),
        "ECONNABORTED"      => Value::int(103),
        "ECONNRESET"        => Value::int(104),
        "ENOBUFS"           => Value::int(105),
        "EISCONN"           => Value::int(106),
        "ENOTCONN"          => Value::int(107),
        "ESHUTDOWN"         => Value::int(108),
        "ETOOMANYREFS"      => Value::int(109),
        "ETIMEDOUT"         => Value::int(110),
        "ECONNREFUSED"      => Value::int(111),
        "EHOSTDOWN"         => Value::int(112),
        "EHOSTUNREACH"      => Value::int(113),
        "EALREADY"          => Value::int(114),
        "EINPROGRESS"       => Value::int(115),
        "ESTALE"            => Value::int(116),
        "EUCLEAN"           => Value::int(117),
        "ENOTNAM"           => Value::int(118),
        "ENAVAIL"           => Value::int(119),
        "EISNAM"            => Value::int(120),
        "EREMOTEIO"         => Value::int(121),
        "EDQUOT"            => Value::int(122),
        "ENOMEDIUM"         => Value::int(123),
        "EMEDIUMTYPE"       => Value::int(124),
        "ECANCELED"         => Value::int(125),
        "ENOKEY"            => Value::int(126),
        "EKEYEXPIRED"       => Value::int(127),
        "EKEYREVOKED"       => Value::int(128),
        "EKEYREJECTED"      => Value::int(129),
        "EOWNERDEAD"        => Value::int(130),
        "ENOTRECOVERABLE"   => Value::int(131),
        "ERFKILL"           => Value::int(132),
        // EDEADLOCK is an alias for EDEADLK on Linux.
        "EDEADLOCK"         => Value::int(35),

        // errorcode: maps int code → canonical name string.
        "errorcode"         => make_errorcode(),
    }
}
